version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/.env:/app/.env
    command: npm run dev
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
      - ./db:/docker-entrypoint-initdb.d

volumes:
  mongo-data: